{
  "name": "208.py",
  "type": "CFG",
  "blocks": [
    {
      "id": 1,
      "label": "#1\nimport asyncio\nimport pytest\nfrom backend.util.retry import conn_retry",
      "successors": []
    }
  ],
  "functions": [
    {
      "name": "test_conn_retry_sync_function",
      "type": "CFG",
      "blocks": [
        {
          "id": 3,
          "label": "#3\nretry_count = 0\nretry_count = 2\nres = test_function()\nassert res == 'Success'",
          "successors": [
            {
              "id": 12,
              "label": "#12\nretry_count = 100\nwith pytest.raises(ValueError) as e:",
              "successors": [
                {
                  "id": 13,
                  "label": "#13\ntest_function()\nassert str(e.value) == 'Test error'",
                  "successors": []
                }
              ]
            }
          ]
        }
      ],
      "functions": [
        {
          "name": "test_function",
          "type": "CFG",
          "blocks": [
            {
              "id": 5,
              "label": "#5\nnonlocal retry_count\nretry_count -= 1\nif retry_count > 0:",
              "successors": [
                {
                  "id": 6,
                  "label": "#6\nraise ValueError('Test error')",
                  "successors": []
                },
                {
                  "id": 7,
                  "label": "#7\nreturn 'Success'",
                  "successors": []
                }
              ]
            }
          ],
          "functions": [],
          "classes": []
        }
      ],
      "classes": []
    },
    {
      "name": "test_conn_retry_async_function",
      "type": "CFG",
      "blocks": [
        {
          "id": 19,
          "label": "#19\nretry_count = 0\nretry_count = 2\nres = await test_function()",
          "successors": [
            {
              "id": 28,
              "label": "#28\nassert res == 'Success'",
              "successors": [
                {
                  "id": 30,
                  "label": "#30\nretry_count = 100\nwith pytest.raises(ValueError) as e:",
                  "successors": [
                    {
                      "id": 31,
                      "label": "#31\nawait test_function()",
                      "successors": [
                        {
                          "id": 33,
                          "label": "#33\nassert str(e.value) == 'Test error'",
                          "successors": []
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ],
      "functions": [
        {
          "name": "test_function",
          "type": "CFG",
          "blocks": [
            {
              "id": 21,
              "label": "#21\nnonlocal retry_count\nawait asyncio.sleep(1)",
              "successors": [
                {
                  "id": 22,
                  "label": "#22\nretry_count -= 1\nif retry_count > 0:",
                  "successors": [
                    {
                      "id": 23,
                      "label": "#23\nraise ValueError('Test error')",
                      "successors": []
                    },
                    {
                      "id": 24,
                      "label": "#24\nreturn 'Success'",
                      "successors": []
                    }
                  ]
                }
              ]
            }
          ],
          "functions": [],
          "classes": []
        }
      ],
      "classes": []
    }
  ],
  "classes": []
}